name: Test Dynatrace Canary Exporter

on:
  pull_request:
    branches: [ master ]
    paths: 
      - 'third-party-synthetic/aws-cloudwatch/**'

jobs:
  build:
    name: Test Dynatrace Canary Exporter

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./third-party-synthetic/aws-cloudwatch

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm test
